using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RD._Content.UI.Character;

[GenerateTypedNameReferences]
public sealed partial class RDCharacterEditorWindow : DefaultWindow
{
    public RDCharacterEditorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TabContainer.SetTabTitle(0, "Characteristics");
        TabContainer.SetTabTitle(1, "Skills");
        TabContainer.SetTabTitle(2, "Traits");
        TabContainer.SetTabTitle(3, "Description");
    }
}
