using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RD._Content.UI.Character;

[GenerateTypedNameReferences]
public sealed partial class RDCharacterEditorTraitsControl : Control
{
    public RDCharacterEditorTraitsControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
