using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RD._Content.UI.Lobby;

[GenerateTypedNameReferences]
public sealed partial class RDLobbyUI : UIScreen
{
    public RDLobbyUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
