using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RD.Exchanger;

[GenerateTypedNameReferences]
public sealed partial class RDExchangerWindow : DefaultWindow
{
    public RDExchangerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
