using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RD.Perks.UI;

[GenerateTypedNameReferences]
public sealed partial class RDPerkWindow : DefaultWindow
{
    public RDPerkWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
