using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RD.Perks.UI;

[GenerateTypedNameReferences]
public sealed partial class RDPerkTreeButtonControl : Control
{
    public event Action? OnPressed;

    public RDPerkTreeButtonControl(Color color, string label)
    {
        RobustXamlLoader.Load(this);

        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        SkillTreeLabel.Text = label;

        MainButton.OnPressed += _ => OnPressed?.Invoke();
    }
}
