using Content.Shared._RD.Character;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RD._Content.UI.Lobby.Character.Editor;

[GenerateTypedNameReferences]
public sealed partial class RDCharacterEditorWindow : DefaultWindow
{
    public RDCharacterProfile Profile = RDCharacterProfile.Default;

    public RDCharacterEditorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DescriptionControl.Startup(this);

        TabContainer.SetTabTitle(0, "Characteristics");
        TabContainer.SetTabTitle(1, "Skills");
        TabContainer.SetTabTitle(2, "Traits");
        TabContainer.SetTabTitle(3, "Description");
    }
}
